spring.application.name=springEurkaServer
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.use-dns-for-fetching-service-urls=false
eureka.client.prefer-same-zone-eureka=false




