spring.application.name=eurekaserver
server.port=8761

# Disabling Eureka client behavior as this is the Eureka server itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation mode (caution in production)
eureka.server.enable-self-preservation=false

# Set the service URL for other services to register with Eureka (docker container name or localhost)
eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka

# These are good defaults for your case
eureka.client.use-dns-for-fetching-service-urls=false
eureka.client.prefer-same-zone-eureka=false
